version: "3.8"
services: 
  frontend:
    container_name: frontend
    build: ./client
    env_file:
      - ./client/.env
    ports:
      - "3000:3000"
    depends_on: 
      - backend
    networks:
      - mynetwork

  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always  
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mynetwork
      
  backend:
    container_name: backend
    build: ./server
    env_file:
      - ./server/.env
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    networks:
      - mynetwork
      
networks:
  mynetwork:
    driver: bridge      
volumes:
  mongo_data:
